community/urls.py
from django.urls import path ,include
from community import views

app_name='community'

urlpatterns = [
    path('',views.post_view, name='post_view'),
    path('write/',views.post_write, name='post_write'),
    path('<int:article_id>/',views.article_detail, name="detail"),
]

turtle_insta/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('community/',include('community.urls')),
]

users/urls.py
from django.urls import path ,include
from users import views

# 장고가 알아보기 위해
app_name = 'users'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('user/', views.user, name='user'),
    path('<str:username>/', views.profile, name='profile'),
]

community/models.py
from turtle import title
from xml.etree.ElementTree import Comment
from django.db import models
from users.models import User

# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True) #자동생성
    edite_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.title)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    profile = models.TextField(max_length=500, blank=True)
    

community/views.py
import re
from turtle import title
from django.http import HttpResponse
from django.shortcuts import render, redirect
from community.models import Articles
from django.shortcuts import get_object_or_404
# Create your views here.
def post_view(request):
    all_article = Articles.objects.all().order_by('-create_at')
    context = {
        'all_article':all_article
    }
    return render(request,'show.html',context)

def post_write(request):
    if request.method == 'GET':
        return render(request,'write.html')
    elif request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        Articles.objects.save(title=title, content=content, user = request.user)
        return redirect('community:post_view')

def article_detail(request,article_id):
    article = get_object_or_404(Articles, id=article_id)
    context = {
        "article": article
    }
    return render(request,'detail.html',context)

users/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import User
from django.contrib.auth import authenticate, login
from django.shortcuts import get_object_or_404

# Create your views here.
def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        passwordcheck = request.POST.get('passwordcheck')
        if password == passwordcheck:
            User.objects.create_user(username=username, password=password)
            return redirect('users:login')
        else:
            return HttpResponse('비밀번호 확인 틀렸습니다.')

def login_view(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # authenticate가 있는지 없는지 확인해 주는 역활
        user = authenticate(request, username=username, password=password)
        if user:
            # login이 세션을 만들어주는 역활
            login(request, user)
            return redirect('users:user')
        else:
            return render(request,'login.html', {'error':'username or password is incorrect'})

def user(request):
    print(request.user)
    return render(request, 'user.html')

def profile(request, username):
    # user = User.objects.get(username=username)
    user = get_object_or_404(User, username=username)
    context = {
        "user": user
    }
    return render(request, 'profile.html',context)
    

community/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시글 상세페이지</title>
</head>
<body>
    <h1>게시글 상세페이지 입니다.</h1>

    <h2>{{ article.title }}</h2>
    <h3>{{ article.content }}</h3>
    <h4>{{ article.user }}</h4>
</body>
</html>

community/templates/show.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>게시물 보여주기</title>
</head>

<body>
    <h1>게시물 페이지</h1>
    <br>
    <form method="GET" action="{% url 'community:post_write' %}">
        <button>게시물 작성하기</button>
    </form>
    <br>
    {% for article in all_article %}
    <div>
        <a href="{% url 'community:detail' article.id %}">
            <h3>{{ article.title }}</h3>
        </a>
    </div>

    <br>
    {% endfor %}
</body>

</html>

community/templates/write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Write</title>
</head>
<body>
    <h1>게시물 작성 페이지</h1>
    <form action="{% url 'community:post_write' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_subject"> 제목 </label>
            <input type="text" class="form-control" name="title">
        </div>

        <div class="form-group">
            <lable for="id_message">내용</lable>
            <textarea class="form-control" name="content" rows="5"></textarea>
        </div>
        <input type="submit" />
    </form>
</body>
</html>

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인페이지</title>
</head>
<body>
    <h1>로그인 페이지</h1>
    {% if error %}
    {{ error }}
    {% endif %}
    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username"/>
        <input type="password" name="password" placeholder="password"/>
        <input type="submit" />
    </form>
</body>
</html>

users/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>프로필 페이지</title>
</head>
<body>
    {% if user == request.user %}
    <div>내 프로필 페이지</div>
    <button>프로필 편집 버튼</button>
    {% endif %}

    <h1>{{ user }}님의 페이지</h1>
    <p> 마지막 로그인은 {{ user.last_login }}</p>

    <form method="GET" action="{% url 'community:post_view' %}">
        <button>게시물 페이지로 이동</button>
    </form>


</body>
</html>

users/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입</title>
</head>
<body>
    <h1>회원가입 페이지</h1>
    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username"/>
        <input type="password" name="password" placeholder="password"/>
        <input type="password" name="passwordcheck" placeholder="passwordcheck"/>
        <input type="submit" />
    </form>
</body>
</html>

users/templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>usershow</title>
</head>
<body>
    <h1> {{user.username}}님이 로그인 하셨습니다.</h1>
    <h2> {{user.date_joined}} 가입 날짜</h2>
    <form method="GET" action="{% url 'community:post_view' %}">
        <button>게시물 페이지로 이동</button>
    </form>
    <form method="GET" action="{% url 'users:login' %}">
        <button>logout</button>
    </form>

</body>
</html>